spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

springdoc:
  swagger-ui:
    path: /api-docs

jwt:
  secret-string: ${JWT_SECRET_STRING}

oauth:
  kakao-client-key: ${KAKAO_CLIENT_KEY}
  kakao-client-secret: ${KAKAO_CLIENT_SECRET}

host-address: ${HOST_ADDRESS}
