spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1GB

server:
  tomcat:
    max-http-form-post-size: 1GB


springdoc:
  swagger-ui:
    path: /api-docs

jwt:
  secret-string: ${JWT_SECRET_STRING}

oauth:
  kakao-client-key: ${KAKAO_CLIENT_KEY}
  kakao-client-secret: ${KAKAO_CLIENT_SECRET}

host-address: ${HOST_ADDRESS}

errorbot:
  kakao-work:
    key: ${KAKAO_WORK_BOT_KEY}
    room-id: ${KAKAO_WORK_ROOM_ID}

file:
  dir: ${FILE_DIR}